spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/erp_db
    username: admin_erp
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update #create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  cache:
    type: caffeine
